# Generated by Django 3.2.8 on 2021-11-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0002_backimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='BottomCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'bottom_carousel',
            },
        ),
        migrations.CreateModel(
            name='TopCarousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/')),
                ('link', models.URLField(default='')),
            ],
            options={
                'db_table': 'top_carousel',
            },
        ),
        migrations.AddField(
            model_name='backimg',
            name='link',
            field=models.URLField(default=''),
        ),
        migrations.AddField(
            model_name='backimg',
            name='title',
            field=models.CharField(default='', max_length=50),
        ),
    ]
