# Generated by Django 3.2.8 on 2021-12-01 07:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20211130_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='cinema',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='contact',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.contact'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2021, 12, 1)),
        ),
    ]
