# Generated by Django 3.2.8 on 2021-12-01 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0005_auto_20211201_0755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoblock',
            name='description',
        ),
        migrations.AddField(
            model_name='seoblock',
            name='seo_description',
            field=models.TextField(null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='keywords',
            field=models.TextField(verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='seoblock',
            name='url',
            field=models.URLField(max_length=150, verbose_name='Ссылка'),
        ),
    ]
