# Generated by Django 3.2.8 on 2021-12-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0007_hall_seo_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seoblock',
            name='keywords',
            field=models.CharField(max_length=255, verbose_name='Ключевые слова'),
        ),
    ]
