# Generated by Django 3.2.8 on 2021-12-01 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0008_alter_seoblock_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
