# Generated by Django 3.2.8 on 2021-12-05 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0013_alter_newsimg_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='able_to_del',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='logo',
            field=models.ImageField(upload_to=''),
        ),
    ]
