# Generated by Django 3.2.8 on 2021-12-05 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0014_auto_20211205_1818'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='first_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='page',
            name='second_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='page',
            name='third_pic',
            field=models.ImageField(null=True, unique=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
