# Generated by Django 3.2.8 on 2021-12-05 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0016_alter_contact_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinema',
            name='contact',
        ),
        migrations.AddField(
            model_name='contact',
            name='cinema',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema'),
        ),
    ]
