# Generated by Django 3.2.8 on 2021-12-05 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0019_auto_20211205_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='card_img',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='card_img',
        ),
    ]
