# Generated by Django 3.2.8 on 2021-12-05 20:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0022_auto_20211205_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='seo_block',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.seoblock'),
        ),
    ]
