# Generated by Django 3.2.8 on 2021-12-06 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0026_alter_contact_cinema'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='admin_panel.cinema'),
        ),
    ]
