# Generated by Django 3.2.8 on 2021-12-06 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0028_cafebarmenu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafebarmenu',
            name='price',
            field=models.PositiveIntegerField(null=True, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='cafebarmenu',
            name='weight',
            field=models.PositiveIntegerField(null=True, verbose_name='Вес(грамм)'),
        ),
    ]
