# Generated by Django 3.2.8 on 2021-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0033_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
