# Generated by Django 3.2.8 on 2021-12-08 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0034_alter_page_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='creation_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
