# Generated by Django 3.2.8 on 2021-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0035_user_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lang',
            field=models.CharField(choices=[('Русский', 'Русский'), ('Украинскийй', 'Украинский')], default='Русский', max_length=20, verbose_name='Язык'),
        ),
    ]
